sudo: required
language: python
python: 3.7
services:
  - docker

install:
  - docker-compose up --build -d

script:
  - docker exec -it foodcare-api python3 manage.py test

after_script:
  - docker-compose down
