site_name: FoodCare Docs

repo_name: 'fga-eps-mds/2019.2-FoodCare'
repo_url: 'https://github.com/fga-eps-mds/2019.2-FoodCare'

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Barlow'
  logo: 'assets/images/id-visual/icon-white.png'
    # icon: 'restaurant'1
  feature:
    tabs: true

nav:
  - Início: 
    - Home: index.md
    # - Guia de Contribuição: ../CONTRIBUTING.md
    # - Código de Conduta: ../CODE_OF_CONDUCT.md
  - Produto:
    - Documento de Visão: produto/doc-visao.md
    - Documento de Arquitetura: produto/doc-arquitetura.md
    - Mapa Mental: produto/mapa-mental.md
    - Canvas: produto/canvas.md
    - Identidade Visual: produto/id-visual.md
    - Protótipo de Baixa Fidelidade: produto/prototipo-baixa.md
    - Protótipo de Alta Fidelidade: produto/prototipo-alta.md
    - Plano de Gerenciamento de Qualidade: projeto/plano_qualidade.md
    - Especificação Suplementar: produto/especificacao_suplementar.md
  - Projeto:
    - Termo de Abertura de Projeto: produto/tap.md
    - Estrutura Analítica do Projeto: produto/eap.md
    - Plano de Gerência de Configuração de Software: projeto/gcs.md
    - Metodologia: projeto/metodologia.md
    - RoadMap do Projeto: projeto/roadmap-projeto.md
    - RoadMap de Papéis: projeto/roadmap-papeis.md
    - Pipeline: projeto/pipeline.md
    - Ferramentas: projeto/ferramentas.md
    - Plano de Risco: projeto/plano-risco.md
    - Product Backlog: projeto/product-backlog.md
    - Reuniões:
      - Reunião 01: projeto/reunioes/reuniao_01.md
      - Reunião 02: projeto/reunioes/reuniao_02.md
      - Reunião 03: projeto/reunioes/reuniao_03.md
      - Reunião 04: projeto/reunioes/reuniao_04.md
      - Reunião 05: projeto/reunioes/reuniao_05.md
  - Sprints:
    - Sprint 0:
      - Planejamento Sprint 0: sprints/00/planejamento_0.md
      - Resultado Sprint 0: sprints/00/resultado_0.md
    - Sprint 1:
      - Planejamento Sprint 1: sprints/01/planejamento_1.md
      - Resultado Sprint 1: sprints/01/resultado_1.md
    - Sprint 2:
      - Planejamento Sprint 2: sprints/02/planejamento_2.md
      - Resultado Sprint 2: sprints/02/resultado_2.md
    - Sprint 3:
      - Planejamento Sprint 3: sprints/03/planejamento_3.md
      - Resultado Sprint 3: sprints/03/resultado_3.md
    - Sprint 4:
      - Planejamento Sprint 4: sprints/04/planejamento_4.md
      - Resultado Sprint 4: sprints/04/resultado_4.md
    - Sprint 5:
      - Planejamento Sprint 5: sprints/05/planejamento_5.md
      - Resultado Sprint 5: sprints/05/resultado_5.md
    # - Sprint 6:
    #   - Planejamento Sprint 4: sprints/06/planejamento_6.md
    #   - Resultado Sprint 4: sprints/06/resultado_6.md
