site_name: FoodCare Docs

repo_name: 'fga-eps-mds/2019.2-FoodCare'
repo_url: 'https://github.com/fga-eps-mds/2019.2-FoodCare'

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Barlow'
  logo: 'assets/images/id-visual/icon-white.png'
  feature:
    tabs: true

nav:
  - Início: 
    - Home: index.md
  - Produto:
    - Documento de Visão: produto/doc-visao.md
    - Documento de Arquitetura: produto/doc-arquitetura.md
    - Mapa Mental: produto/mapa-mental.md
    - Canvas: produto/canvas.md
    - Identidade Visual: produto/id-visual.md
    - Protótipo de Baixa Fidelidade: produto/prototipo-baixa.md
    - Protótipo de Alta Fidelidade: produto/prototipo-alta.md
    - Product Backlog: produto/product-backlog.md
    - Especificação Suplementar: produto/especificacao_suplementar.md
  - Projeto:
    - Termo de Abertura de Projeto: projeto/tap.md
    - Estrutura Analítica do Projeto: projeto/eap.md
    - Metodologia: projeto/metodologia.md
    - Ferramentas: projeto/ferramentas.md
    - Plano de Gerenciamento de Qualidade: projeto/plano_qualidade.md
    - Plano de Gerência de Configuração de Software: projeto/gcs.md
    - RoadMap de Papéis: projeto/roadmap-papeis.md
    - RoadMap do Projeto: projeto/roadmap-projeto.md
    - Pipeline de DevOps: projeto/pipeline.md
    - Plano de Risco: projeto/plano-risco.md
    - ROI: projeto/roi.md
    - EVM: projeto/evm.md
    - Reuniões:
      - Reunião 01: projeto/reunioes/reuniao_01.md
      - Reunião 02: projeto/reunioes/reuniao_02.md
      - Reunião 03: projeto/reunioes/reuniao_03.md
      - Reunião 04: projeto/reunioes/reuniao_04.md
      - Reunião 05: projeto/reunioes/reuniao_05.md
      - Reunião 06: projeto/reunioes/reuniao_06.md
  - Sprints:
    - Sprint 0:
      - Planejamento Sprint 0: projeto/sprints/00/planejamento_0.md
      - Resultado Sprint 0: projeto/sprints/00/resultado_0.md
    - Sprint 1:
      - Planejamento Sprint 1: projeto/sprints/01/planejamento_1.md
      - Resultado Sprint 1: projeto/sprints/01/resultado_1.md
    - Sprint 2:
      - Planejamento Sprint 2: projeto/sprints/02/planejamento_2.md
      - Resultado Sprint 2: projeto/sprints/02/resultado_2.md
    - Sprint 3:
      - Planejamento Sprint 3: projeto/sprints/03/planejamento_3.md
      - Resultado Sprint 3: projeto/sprints/03/resultado_3.md
    - Sprint 4:
      - Planejamento Sprint 4: projeto/sprints/04/planejamento_4.md
      - Resultado Sprint 4: projeto/sprints/04/resultado_4.md
    - Sprint 5:
      - Planejamento Sprint 5: projeto/sprints/05/planejamento_5.md
      - Resultado Sprint 5: projeto/sprints/05/resultado_5.md
    - Sprint 6:
      - Planejamento Sprint 6: projeto/sprints/06/planejamento_6.md
      - Resultado Sprint 6: projeto/sprints/06/resultado_6.md
    - Sprint 7:
      - Planejamento Sprint 7: projeto/sprints/07/planejamento_7.md
      - Resultado Sprint 7: projeto/sprints/07/resultado_7.md
    - Sprint 8:
      - Planejamento Sprint 8: projeto/sprints/08/planejamento_8.md
      - Resultado Sprint 8: projeto/sprints/08/resultado_8.md
    - Sprint 9:
      - Planejamento Sprint 9: projeto/sprints/09/planejamento_9.md
      - Resultado Sprint 9: projeto/sprints/09/resultado_9.md
    - Sprint 10:
      - Planejamento Sprint 10: projeto/sprints/10/planejamento_10.md
      - Resultado Sprint 10: projeto/sprints/10/resultado_10.md
    - Sprint 11:
      - Planejamento Sprint 11: projeto/sprints/11/planejamento_11.md
      - Resultado Sprint 11: projeto/sprints/11/resultado_11.md
    - Sprint 12:
      - Planejamento Sprint 12: projeto/sprints/12/planejamento_12.md
      - Resultado Sprint 12: projeto/sprints/12/resultado_12.md
    - Sprint 13:
      - Planejamento Sprint 13: projeto/sprints/13/planejamento_13.md
      - Resultado Sprint 13: projeto/sprints/13/resultado_13.md
  - Postmortem:
    - Postmortem: projeto/post-mortem.md

